# config_main.yaml

# Main configuration

# Defaults (changeable through command line or specific runs)
defaults:
  - prior: normal1D #normal1D
  - target: normal1D #normal1D  #OPTIONS: normal1D, gaussian_mixture, donut
  - solver: svgd      #OPTIONS: kfrflow, svgd
  - integrator: RK45    #OPTIONS: ExplicitEuler, RK45
  - integrand: squared #OPTIONS: identity, squared_norm
  - kernel: RBF #OPTIONS: InverseMultiquadric, RBF
  - override hydra/launcher: joblib
  - _self_

run_dir:
prior_sampling_constr: Halton #OPTIONS: Halton, Random
num_samples_constr: 256
load_data: null #<your-file-path>
prior_sampling_eval: Halton #OPTIONS: Halton, Random
num_samples_eval: 256
seed:

# Hydra settings
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  launcher:
    n_jobs: 1
  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: computations.log
    root:
      level: WARNING
      handlers: [file]